services:
  db:
    image: postgres:18.1
    container_name: db
    restart: no
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    shm_size: 128mb
    volumes:
      - ./postgres_data:/var/lib/postgresql
